### ISSUE TITLE
Feature - Import dbt_could_bigquery_connection

### ISSUE THREAD

**Issue by EvavW** [dbt-labs/terraform-provider-dbtcloud#110]
Thanks for adding the [dbt_cloud_bigquery_connection](https://github.com/GtheSheep/terraform-provider-dbt-cloud/pull/107) resource. I'd like to be able to import an existing resource i.e.

 `terraform import dbt_cloud_bigquery_connection.test_connection "project_id:connection_id"`

I realize this was added only 3 weeks ago. Do you have an idea of when the import feature will be added? I'd be happy to contribute to the work if possible.
Thanks!

**Comment by b-per** [comment]
I just tried the exact syntax that you shared and it worked for me. Would you be able to share the issue/error that you face when you run the command?

**Comment by GtheSheep** [comment]
@EvavW - did you get a chance to try this out? Might've just been included in a newer release than when you happened to test before 😸

**Comment by BenLiyanage** [comment]
Definitely would appreciate this being in the documentation.

**Comment by b-per** [comment]
I am doing some updates to the docs, (adding examples, guides etc...) and will definitely take that feedback into account. I will add the import statements for all the different resources that support it (which should be all of them as the `import` is handled automatically by the Terraform SDK).

In the meantime, I will close this issue as the import feature is already supported (while not documented)

**Comment by b-per** [comment]
Docs have been updated in 0.2.2 (being released right now), and `import` are added for all resources
