### ISSUE TITLE
`terraform import dbt_cloud_project.*` deletes existing dbt Cloud configuration

### ISSUE THREAD

**Issue by waligob** [dbt-labs/terraform-provider-dbtcloud#111]
We have identified an issue with the [dbt_cloud_project](https://registry.terraform.io/providers/GtheSheep/dbt-cloud/latest/docs/resources/dbt_cloud_project) resource: running the import command `terraform import dbt_cloud_project.<project_name> <project_id>` deletes the existing project configuration. Here is the command run:
```console
$ terraform import dbt_cloud_project.analytics 62160
var.dbt_cloud_api_key
  Enter a value: 

dbt_cloud_project.analytics: Importing from ID "62160"...
dbt_cloud_project.analytics: Import prepared!
  Prepared dbt_cloud_project for import
dbt_cloud_project.analytics: Refreshing state... [id=62160]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

After about 15 minutes, the configuration for an established project is no longer available:
![image](https://user-images.githubusercontent.com/93673562/221909587-9342cdab-e3d1-45da-baf0-faba42fa3def.png)
_Note the project was named `Analytics_old` previously, but it was configured with a BigQuery connection, not Snowflake_

**Comment by GtheSheep** [comment]
Hi there! Could you elaborate a little more on this comment please, I'm not sure I quite understand?
```Note the project was named Analytics_old previously, but it was configured with a BigQuery connection, not Snowflake```

Following on from this, did you run any further commands? Are any other resources managed in Terraform? Could you also let me know the provider version please.
Has the issue repeated if you've tried it again at all? I did this on my own project with no worries and haven't been able to replicate this yet.
