### ISSUE TITLE
issue when redeploying a dbt cloud job

### ISSUE THREAD

**Issue by do-groupm** [dbt-labs/terraform-provider-dbtcloud#141]
Stack trace from the terraform-provider-dbt-cloud_v0.1.9 plugin:
panic: interface conversion: interface {} is nil, not bool
goroutine 83 [running]:
github.com/gthesheep/terraform-provider-dbt-cloud/pkg/resources.resourceJobUpdate({0xcd2088, 0xc000098f00}, 0xc000130880, {0xbc1340, 0xc00005e980})
	github.com/gthesheep/terraform-provider-dbt-cloud/pkg/resources/job.go:353 +0x12c7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0003d6c40, {0xcd20c0, 0xc00011f4a0}, 0xd, {0xbc1340, 0xc00005e980})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:376 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0003d6c40, {0xcd20c0, 0xc00011f4a0}, 0xc000377520, 0xc000130700, {0xbc1340, 0xc00005e980})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:482 +0x785
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000121140, {0xcd2018, 0xc00012ca40}, 0xc0005702d0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003de0a0, {0xcd20c0, 0xc0001e9950}, 0xc0000f2d20)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x56b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xba[150](https://gitlab.com/2sixty/datacloud/dc-units/unit-001/unit-0001-dev-runner-5/-/jobs/4307641990#L150)0, 0xc0003de0a0}, {0xcd20c0, 0xc0001e9950}, 0xc000589440, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014a700, {0xcdedf8, 0xc0004141a0}, 0xc000677c20, 0xc0003f0e70, 0x119db20, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc00014a700, {0xcdedf8, 0xc0004141a0}, 0xc000677c20, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x294
Error: The terraform-provider-dbt-cloud_v0.1.9 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by GtheSheep** [comment]
Hey, thanks for submitting!

Could you provide some details please, redeploying = updating? What did you change? What kind of configurations are on the job? Thanks
