### ISSUE TITLE
updating schedule_hours/schedule_interval in a dbtcloud_job does not change in dbt cloud

### ISSUE THREAD

**Issue by justbldwn** [dbt-labs/terraform-provider-dbtcloud#172]
hi, running into a somewhat strange bug when importing and updating dbtcloud_jobs. we are currently in the process of importing existing dbtcloud_jobs via terraform and looking to standardize a "Generate Docs" job for all of our projects in the process. 

when running a plan, we can see a docs job is queued for an updated based on our new module definition:

![terraform_docs_update](https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/91483530/3781274b-02ee-4b54-81cc-3549530400ce)

after running apply, terraform says that the docs job was updated:
![terraform_docs_updated](https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/91483530/049c71ed-8e46-4570-88da-668d7582fdcf)

if i immediately trigger a new run after the apply finishes, it wants to update the same generate_docs again with the same info as the first screenshot. it wasn't until i manually updated the dbt cloud UI directly with the terraform changes and triggered a new terraform plan for terraform to recognize that the changes were made and stopped trying to update the generate_docs job.

is this something you could look into to see if changing a job schedule_hours/schedule_interval is working properly? i'm not sure if the issue is limited to those fields specifically, or if updating an existing job is just not working properly overall, but wanted to raise this for you to investigate. thanks!

**Comment by b-per** [comment]
Hi! Thanks for raising an issue here.

Would you be able to share the full content of the job config so I can try to reproduce the issue?

**Comment by justbldwn** [comment]
sure thing! here is an example we're using to define our job config inside our module:

`locals.tf`
```hcl
  project_settings = {
    dev = {
      env_variables = {...}
      environments = [
        {
          name = "Development"
          type = "development"
          env_variables = {...}
        },
        {
          name = "DEV Deployment"
          type = "deployment"
          env_variables = {...}
        },
      ]
    }
    qa = {
      env_variables = {...},
      environments = [
        {
          name = "QA"
          type = "deployment"
          env_variables = {...}
        }
      ]
    }
    prd = {
      env_variables = {...},
      environments = [
        {
          name = "Production"
          type = "deployment"
          env_variables = {...},
        }
      ]
    }
  }
```

`module.tf`
```hcl
resource "dbtcloud_job" "generate_docs" {
  for_each = { for e in local.project_settings[var.env].environments : e.name => e if e.name != "Development" }

  environment_id = dbtcloud_environment.environment[each.value.name].environment_id
  execute_steps = [
    "dbt compile"
  ]
  generate_docs = true
  name          = "Generate Docs"
  project_id    = dbtcloud_project.project.id
  triggers = {
    "custom_branch_only" : true,
    "github_webhook" : false,
    "git_provider_webhook" : false,
    "schedule" : true
  }
  num_threads = 4

  schedule_days     = [0, 1, 2, 3, 4, 5, 6]
  schedule_type     = "days_of_week"
  schedule_interval = 6
}
```
