### ISSUE TITLE
enhance log messages when importing/creating deployment environments without credential_id

### ISSUE THREAD

**Issue by justbldwn** [dbt-labs/terraform-provider-dbtcloud#173]
i was recently working through importing environments for a project and hit the below error when importing 2 deployment environments.

```python3
Error: POST
url: https://cloud.getdbt.com/api/v3/accounts/[account_id]/projects/[project_id]/environments/[environment_id]/,
status: 500,
body: {
    "status":{
        "code":500,
        "is_success":false,
        "user_message":"There was a server error. Please contact support!",
        "developer_message":""
    },
    "data":null
}
```

after looking into this without any log context, the cause of the error seemed to be due to the credential_id not being properly set in the environment module when importing the environment. once i added a configuration for the credential_id to be set on deployment environments, the environment import worked and this error went away.

as a QoL feature, and one that could help reduce the research for not having the environment setup properly, can the log message be updated here to provide info that a deployment environment requires a credential_id if it's not provided when either importing/creating environments? thanks!

**Comment by b-per** [comment]
This is part of the proprietary code of dbt Cloud so there is no external contribution possible. I can pass the feedback to the team though.
