### ISSUE TITLE
Feature: add support for execution project on bigquery jobs

### ISSUE THREAD

**Issue by matt-winkler** [dbt-labs/terraform-provider-dbtcloud#183]
Bigquery execution project is a key variable for controlling dbt Cloud job spend within bigquery. It would be great if this could be enabled via the provider (community feedback). Feel free to let me know if this a "good first issue" candidate.

**Comment by b-per** [comment]
It's already supported since 0.2.6 with https://github.com/dbt-labs/terraform-provider-dbtcloud/pull/164 😉

**Comment by matt-winkler** [comment]
Hey @b-per to be clear, the request is to enable setting this at the **job level** vs. the connection level. The PR you linked appears to be connection level. Seems there are couple of dependencies here. 1) need to support the ability to set this on the job level in dbt Cloud and 2) enable making that setting via Terraform.

**Comment by b-per** [comment]
Ohhh, OK. Let's keep it open then.

With extended attributes though it will soon be possible to set it up at the env level in dbt Cloud at least. (and extended attributes should be supported in Terraform soon after they are available in dbt Cloud)

**Comment by matt-winkler** [comment]
Hey @b-per can you confirm [this](https://github.com/dbt-labs/terraform-provider-dbtcloud/blob/main/examples/resources/dbtcloud_extended_attributes/resource.tf) is the extended attributes setting at the environment level? Looks like it just would appreciate a quick yes / no.

**Comment by b-per** [comment]
It is. [The docs on the registry](https://dbtcloud.zendesk.com/agent/tickets/55938/organization/tickets) actually has a bit more info.
