### ISSUE TITLE
Unable to deploy Groups to dbt using the provider

### ISSUE THREAD

**Issue by marychaudry** [dbt-labs/terraform-provider-dbtcloud#207]
When trying to use the resource: resource "dbt_cloud_group" it is giving error: 
Error: POST url: https://<dbt url>/api/v3/accounts/<acc no>/groups/, status: 404, body: {"status":{"code":404,"is_success":false,"user_message":"The requested resource was not found. Please check that you have the proper permissions. If you are seeing this in error, please contact support!","developer_message":""},"data":null}

**Comment by b-per** [comment]
Hi!

Could you please share a sanitised version for the config of the group?

And is the error message the full one you are getting back from the provider? 
Or did you remove your account number etc.. (the URL just looks odd)

**Comment by marychaudry** [comment]
I did not add actual url so its like placeholders as I cannot share actual url


Maria Chaudry

Data Operations Engineer



Mobile: 07360653015

Email: ***@***.******@***.***>

www.three.co.uk<http://www.three.co.uk>

Life Needs a Big Network

[cid:ff609bad-a5fc-4033-bcf1-10a3f2084ea2][cid:bf61995f-f96b-4654-9496-125062dfc7f0]



________________________________

**Comment by b-per** [comment]
OK, thanks for clarifying.

Would it be possible to share the group config though? You can change any sensitive information but it will help me to know what fields are being used.

**Comment by marychaudry** [comment]
This is snippet of apply

# module.<module_name>.module.dbt-cloud-group.dbt_cloud_group.dbt-cloud-group["group_developer"] will be created
  + resource "dbt_cloud_group" "dbt-cloud-group" {
      + assign_by_default  = false
      + id                 = (known after apply)
      + is_active          = true
      + name               = "<name>"
      + sso_mapping_groups = [
          + "<id>",
        ]

      + group_permissions {
          + all_projects   = false
          + permission_set = "developer"
          + project_id     = <id>
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
module.<module_name>.dbt_cloud_group.dbt-cloud-group["group_developer"]: Creating...

Error: POST url: https://<url>/api/v3/accounts/<acc no>/groups/, status: 404, body: {"status":{"code":404,"is_success":false,"user_message":"The requested resource was not found. Please check that you have the proper permissions. If you are seeing this in error, please contact support!","developer_message":""},"data":null}

  with module.<module_name>.module.dbt-cloud-group.dbt_cloud_group.dbt-cloud-group["group_developer"],
  on .terraform/modules/<module_name>/terraform-modules/dbt/module-group/module-group.tf line 11, in resource "dbt_cloud_group" "dbt-cloud-group":
  11: resource "dbt_cloud_group" "dbt-cloud-group" {


 and provider I am using is:

"GtheSheep/dbt-cloud"



Maria Chaudry

Data Operations Engineer



Mobile: 07360653015

Email: ***@***.******@***.***>

www.three.co.uk<http://www.three.co.uk>

Life Needs a Big Network

[cid:cdedf0d7-ba65-4e9d-9c61-06aab377bdb3][cid:84a7f307-0baf-46b3-ae81-50a2f67a2377]



________________________________

**Comment by b-per** [comment]
I will try to replicate it in the latest version of the provider, but please be aware that the version you are using which is no longer maintained and the new provider is [dbt-labs/dbtcloud](https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest).

There is [some info here](https://github.com/dbt-labs/terraform-provider-dbtcloud/blob/main/UPGRADING_PROVIDER.md) on how to switch from the previous one to the new one.

If there is actually a bug, we could fix it in dbt-labs/dbtcloud but there is no way to fix/update GtheSheep/dbt-cloud anymore.

**Comment by marychaudry** [comment]
oh okay so we should use this provider thanks I will try with that in that case


Maria Chaudry

Data Operations Engineer



Mobile: 07360653015

Email: ***@***.******@***.***>

www.three.co.uk<http://www.three.co.uk>

Life Needs a Big Network

[cid:290f5e59-ff57-473d-bd6c-d7785c1debde][cid:001671ae-cc77-4de6-b1c2-00a418c1328a]



________________________________

**Comment by b-per** [comment]
@marychaudry , by the way, just be aware that when you reply to the GH comments by email it adds some personal details. I have been editing your last messages to remove them but I just wanted to let you know.

**Comment by marychaudry** [comment]
okay Ill delete the above messages didn't realize thanks for above :)

**Comment by b-per** [comment]
Let me know how it goes with the "new" provider. And if there is the same issue, I would just need to get the config that you shared before to try to replicate and fix it.

**Comment by marychaudry** [comment]
Sure let me put it here: This is snippet of apply 

# module.<module_name>.module.dbt-cloud-group.dbt_cloud_group.dbt-cloud-group["group_developer"] will be created
  + resource "dbt_cloud_group" "dbt-cloud-group" {
      + assign_by_default  = false
      + id                 = (known after apply)
      + is_active          = true
      + name               = "<name>"
      + sso_mapping_groups = [
          + "<id>",
        ]

      + group_permissions {
          + all_projects   = false
          + permission_set = "developer"
          + project_id     = <id>
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
module.<module_name>.dbt_cloud_group.dbt-cloud-group["group_developer"]: Creating...

Error: POST url: https://<url>/api/v3/accounts/<acc no>/groups/, status: 404, body: {"status":{"code":404,"is_success":false,"user_message":"The requested resource was not found. Please check that you have the proper permissions. If you are seeing this in error, please contact support!","developer_message":""},"data":null}

  with module.<module_name>.module.dbt-cloud-group.dbt_cloud_group.dbt-cloud-group["group_developer"],
  on .terraform/modules/<module_name>/terraform-modules/dbt/module-group/module-group.tf line 11, in resource "dbt_cloud_group" "dbt-cloud-group":
  11: resource "dbt_cloud_group" "dbt-cloud-group" {

**Comment by marychaudry** [comment]
Hi I have tried using the provider:  

 required_providers {
    dbtcloud = {
      source = "dbt-labs/dbtcloud"
      version = "0.2.12"
    } 

but it is still not able to apply the groups:
 
module.dbt_bds_bureau_project.module.dbt-cloud-group.dbtcloud_group.dbt-cloud-group["group_developer"] will be created
  resource "dbtcloud_group" "dbt-cloud-group" {
      assign_by_default  = false
      id                 = (known after apply)
      is_active          = true
      name               = "<product>_dbt_nonprod_deployer"
      sso_mapping_groups = [
           "<>",
        ]
      group_permissions {
          all_projects   = false
          permission_set = "developer"
          project_id     = <prj_id>
        }
    }

**Comment by b-per** [comment]
Thanks, I will try on my side then.

**Comment by b-per** [comment]
I tried the same config on my side and it is working fine.

@marychaudry , could you please raise a support ticket from dbt Cloud about this issue? I guess that you are on Single Tenant, no?

In that case, when getting in touch with support, please tell them that your account is on ST and you are getting a 404 on one of the v3 API endpoints.

**Comment by marychaudry** [comment]
Yes we are single tenant so maybe it is because of that


Maria Chaudry

Data Operations Engineer



Mobile: 07360653015

Email: ***@***.******@***.***>

www.three.co.uk<http://www.three.co.uk>

Life Needs a Big Network

[cid:59c5dc31-3c3d-4a24-b78e-0c93c55af5a0][cid:58806643-e18d-446e-9ca9-bf76b327a47d]



________________________________

**Comment by b-per** [comment]
Hi @marychaudry. Did you end raising a ticket with support? If so, do you have a number I could check?

**Comment by marychaudry** [comment]
Your request (56913) has been updated.

**Comment by b-per** [comment]
Thinking about it a bit more now, what token to you use for connecting to Terraform?
- a personal token?
- a service token? and if so, what permissions does this token have?

I am wondering if this is not related to the token not having the access required

**Comment by marychaudry** [comment]
It is service token, I will check what permission token has

**Comment by jeremyyeo** [comment]
A service token requires either [of these roles](https://docs.getdbt.com/docs/cloud/manage-access/enterprise-permissions) in order to create dbt Cloud user groups:
* Account Admin
* Security Admin

I believe @marychaudry was able to resolve the problem after creating a token with one of the roles mentioned above so it was indeed a permission issue (or lack thereof).

**Comment by b-per** [comment]
Thanks @jeremyyeo !
I wish we returned a 401 instead of a 404...

**Comment by jeremyyeo** [comment]
Fwiw - some services return 404 when you are unauthorized to access a resource in order to not provide any information at all (no information) vs providing some information that a resource exist but you are unauthorized (more information that before).

[GitHub does this.](https://docs.github.com/en/rest/overview/troubleshooting?apiVersion=2022-11-28#404-error-for-an-existing-repository)
