### ISSUE TITLE
Integration dbt repository with Azure DevOps

### ISSUE THREAD

**Issue by dzianisskakalski81** [dbt-labs/terraform-provider-dbtcloud#212]
We are migrating the deployment of our dbt's resources from dbt-cli to Terrarorm.
 
Could you provide some typical Terraform config for the establishment of integration with Azure DevOps repository.
In official documentation there are examples only for GitHub and GitLab.
https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest/docs/resources/repository
 
I am interesting for the values of "remote_url" and "github_instalation_id" in case of using Azure DevOps repository.

**Comment by b-per** [comment]
This should work now with 0.2.14 that I have just relased.

I have added an example to the docs on the Terraform Registry as well
