### ISSUE TITLE
Unable to modify an existing dbt Cloud job

### ISSUE THREAD

**Issue by bsuryachandra** [dbt-labs/terraform-provider-dbtcloud#220]
## Describe the bug
I am unable to update a dbt Cloud job executed through Terraform. Initially, I created the job with **execute_steps: ["dbt build"]**, but later when I updated it to **execute_steps: ["dbt run"]**, it started failing.

## Error message
The error message from running terraform.
<img width="473" alt="image" src="https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/40120313/1c1d3ba6-d668-4cc0-8900-31b7f887337a">
<img width="704" alt="image" src="https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/40120313/e6044419-251d-4c3f-8e95-2e7f71635c24">

## Resource configuration
The relevant resource configuration (sanitised so it doesn't contain sensitive data)
<img width="334" alt="image" src="https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/40120313/c222c527-d953-48ad-8b66-073bd277ea95">

## Expected behavior
Execution steps should be updated with the given new steps

## Config (please complete the following information):
( the version can be retrieved running the command `terraform providers` )
 - dbt Cloud provider version [e.g. 0.2.12]
```
 - terraform {
  required_providers {
    dbtcloud = {
      source  = "dbt-labs/dbtcloud"
      version = "0.2.2"
    }
  }
}
```

**Comment by b-per** [comment]
Hi!

There have been a few bugs fixed since 0.2.2

Could you try with 0.2.15 and see if there is the same problem?

**Comment by bsuryachandra** [comment]
seeing the same issues with 0.2.15 version

**Comment by b-per** [comment]
It looks like you are also removing the `git_provider_webhook` key under `triggers`. Could you keep it set at `false` as it was before?

If it still doesn't work, could you please send across the full config of the resource `dbtcloud_job.test`?

**Comment by bsuryachandra** [comment]
git got executed after setting `git_provider_webhook: false `
thanks @b-per 👍 
i am closing this as it's working expected

**Comment by b-per** [comment]
Thanks for getting back. I might try to update the provider so it doesn't crash at least when this happens and provide a better error message.
