### ISSUE TITLE
Rename `dbtcloud_project_artefacts` to `dbtcloud_project_artifacts`

### ISSUE THREAD

**Issue by b-per** [dbt-labs/terraform-provider-dbtcloud#232]
We should stick to the American spelling

**Comment by BrettMoan** [comment]
Came to github issues to raise a bug for the typo of `artifacts` misspelled as `artefacts`. 

Left learning that the spelling `artefacts` is actually the original British English spelling.

**Comment by b-per** [comment]
Renaming resources is a bit of a pain in Terraform as it will require people to change their configs/modules and update their state but as I don't expect this one to be widely used, I might consider it.

**Comment by will-sargent-dbtlabs** [comment]
@b-per I'm with you. I think as we see folks at scale start to really adopt this, it would be better if the spelling matches dbt clouds spelling for the rest endpoints..

**Comment by will-sargent-dbtlabs** [comment]
Its kind of an odd resource anyway. Not really sure what we are tracking in the state. Seems like more of a data entity but maybe I'm missing the use case here..

**Comment by b-per** [comment]
I will actually deprecate the resource and remove it entirely.

The need to set the default jobs for docs and source freshness doesn't exist anymore with dbt Explorer.
