### ISSUE TITLE
Add correct documentation to `dbtcloud_databricks_credential`

### ISSUE THREAD

**Issue by a-schot** [dbt-labs/terraform-provider-dbtcloud#235]
The documentation for `dbtcloud_fabric_credential` seems to be copied from `dbtcloud_databricks_credential` and is thus not accurate for this resource.

[Link to the doc](https://github.com/dbt-labs/terraform-provider-dbtcloud/blob/main/docs/resources/fabric_credential.md)

dbt Cloud provider version: 0.2.20

**Comment by b-per** [comment]
Thanks! The issue mentions twice `dbtcloud_databricks_credential` , but I am guessing that you meant that the `dbtcloud_fabric_credential`  was copied from the `dbtcloud_databricks_credential` one

I will get the docs updated for the next release!

**Comment by a-schot** [comment]
Awesome! 

> Thanks! The issue mentions twice dbtcloud_databricks_credential , but I am guessing that you meant that the dbtcloud_fabric_credential was copied from the dbtcloud_databricks_credential one

That is indeed what I meant. I corrected the text in the issue
