### ISSUE TITLE
dbtcloud_job keeps trying to change custom_branch_only value

### ISSUE THREAD

**Issue by justbldwn** [dbt-labs/terraform-provider-dbtcloud#239]
## Describe the bug
We have a module for managing our dbt Cloud projects, with a resource in the module to set up a `dbtcloud_job` In it, we have the following triggers defined:

```
  triggers = {
    "custom_branch_only" : true,
    "github_webhook" : false,
    "git_provider_webhook" : false,
    "schedule" : true
  }
```

Each time a Terraform run occurs, we're seeing an update for our dbtcloud_job resource trying to change `custom_branch_only` from `false` to `true` on every project in each environment defined in our Terraform workspace, even though it isn't set with a `custom_branch_only` as false anywhere. Below is an example plan we're seeing:

module.my_project.dbtcloud_job.generate_docs["dev"]
```
id : "123"
name : "Generate Docs"
~ triggers : {
    ~ custom_branch_only : false -> true
    git_provider_webhook : false
    github_webhook : false
    schedule : true
  }
```

When I go to the dbt Cloud UI, the configuration looks correct (the job is set to use a custom branch and the custom branch name defined.

![dbtcloud_job_custom_branch](https://github.com/dbt-labs/terraform-provider-dbtcloud/assets/91483530/29ee8139-16dc-443b-a3aa-9bed411d9fc8)

If I immediately re-plan in our workspace after applying, all `dbtcloud_job.generate_docs` resources want to be updated with the `custom_branch_only : false -> true` change all over again. 

Is this something wrong with our configuration in the triggers section? Is there somewhere the `custom_branch_only: false` value is getting pulled from that may need to be updated? It's causing a lot of clutter in our Terraform workspace since it is trying to make hundreds of unnecessary updates each time we trigger a plan/apply in the workspace.

**Terraform version:** 1.5.2
**dbt Cloud provider version:** ~> 0.2.0

Any help here would be greatly appreciated, thanks!

**Comment by b-per** [comment]
Hi!

`custom_branch_only` at the job level has been deprecated from the dbt Cloud API recently: ([docs](https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Create%20Job)).

So, if we try to set a value `true` for the field, we get some odd behaviour as you could see.

Could you set `"custom_branch_only" : false,` in your module?

I can add some comments in the docs about this particular field not being used anymore.

**Comment by justbldwn** [comment]
thanks, I appreciate the response. if we set `custom_branch_only` to false, are we able to still set a custom branch to point at for the job?

**Comment by b-per** [comment]
Yes.

- for scheduled jobs, it will take the custom branch from the environment it is running on
- for API triggered jobs, it will by default take the custom branch from the environment it is running on unless a custom `git_branch` is mentioned in the [API call payload](https://docs.getdbt.com/dbt-cloud/api-v2#/operations/Trigger%20Job%20Run)

**Comment by b-per** [comment]
Yes, I will create a separate issue to make this field optional in the next version of the provider. 

I will update the docs as well to reflect that the parameter has been deprecated.
