### ISSUE TITLE
Provide data resources that allows to query all jobs from within a project and or environment

### ISSUE THREAD

**Issue by mlavaert** [dbt-labs/terraform-provider-dbtcloud#274]
Currently there is only a data object to get information from a single job.  I would need to be able to query all jobs that exist in the production environment. 

My use case: 

- I want to attach webhooks and notifications to jobs created outside of Terraform. Some teams have developer permissions allowing them to create their own jobs without going throughus.

**Comment by mlavaert** [comment]
That would work! TY

**Comment by b-per** [comment]
`dbtcloud_jobs` is available in 0.3.10 that is getting released
