### ISSUE TITLE
environment_id null when using dbtcloud_environments

### ISSUE THREAD

**Issue by Lusther** [dbt-labs/terraform-provider-dbtcloud#281]
## Describe the bug

environment_id is not filled when using dbtcloud_environments data source.

## Error message
NA

## Resource configuration
```
data "dbtcloud_project" "project" {
  name = "datamart-crm"
}

data "dbtcloud_environments" "envs" {
  project_id     = data.dbtcloud_project.project.id
}

output "output" {
  value       = data.dbtcloud_environments.envs
}
```

## Expected behavior
envrionment_id field in the environment data structure should be filled but it is null.

## Config (please complete the following information):
( the version can be retrieved running the command `terraform providers` )
 - dbt Cloud provider version -> 0.3

## Additional context
NA

**Comment by b-per** [comment]
Hi! Thanks for raising this. I will have a look shortly.
