### ISSUE TITLE
Update on connections settings

### ISSUE THREAD

**Issue by jordiortegonvoi** [dbt-labs/terraform-provider-dbtcloud#282]
Hey there! 

Is there an ETA on updating dbtcloud_connection and dbtcloud_project_connection? Since no so long ago connections were moved into the account object now? I'm down to work on this if needed

**Comment by jordiortegonvoi** [comment]
After testing I realized this is not an enhancement anymore but an issue. Connections can't be created with the latest version of the provider. The schema

`POST url: https://cloud.getdbt.com/api/v3/accounts/4954/projects/377492/connections/, status: 400, body: {"status":{"code":400,"is_success":false,"user_message":"The request was invalid. Please double check the provided data and try again.","developer_message":""}`

**Comment by b-per** [comment]
I am actively working on allowing global connections in TF. For that we will add a `connection_id` to `dbtcloud_environment` and create a new `dbtcloud_global_connection` resource.

But what surprises me is that the current resources should still work though.

Could you share a sanitized version of the resource that is failing?

**Comment by jordiortegonvoi** [comment]
Awesome! And thanks for the quick reply

Here you go:

```
resource "dbtcloud_connection" "snowflake" {
  project_id = dbtcloud_project.project.id
  account    = "xxx"
  type       = "snowflake"
  name       = "Snowflake Connection"
  database   = "xxx"
}

resource "dbtcloud_project_connection" "snowfalke_connection" {
  project_id    = dbtcloud_project.project_data_privacy.id
  connection_id = dbtcloud_connection.snowflake.connection_id
}
``` 

Sanitized error log here:

```
dbtcloud_connection.snowflake: Creating...
╷
│ Error: POST url: https://cloud.getdbt.com/api/v3/accounts/xxx/projects/xxx/connections/, status: 400, body: {"status":{"code":400,"is_success":false,"user_message":"The request was invalid. Please double check the provided data and try again.","developer_message":""},"data":{"details":"{'account': 'xxxx, 'database': 'xxx', 'allow_sso': False, 'client_session_keep_alive': False} is not valid under any of the given schemas"},"extra":{},"error_code":null}
│ 
│   with dbtcloud_connection.snowflake,
│   on connections.tf line 2, in resource "dbtcloud_connection" "snowflake":
│    2: resource "dbtcloud_connection" "snowflake" {
│ 
╵
❌  exit status 1
```

From DBT's API spec it looks like that endpoint is not there anymore. Closest to that one would be:
https://docs.getdbt.com/dbt-cloud/api-v3#/operations/Create%20Account%20Connection

**Comment by b-per** [comment]
OK, so I think that this is not related to the global connection change but you are just missing the `warehouse` config for the data warehouse. Could you try again and let me know?

The new `dbtcloud_global_connection` resource that will be released soon should be better at highlighting missing mandatory fields.

**Comment by b-per** [comment]
The "old" endpoints are removed from the docs as people should be using the new global/account connection going forward, but they should still work from the time being.

**Comment by jordiortegonvoi** [comment]
Confirmed!! Adding the warehouse fixed it. The provider docs didn't mention it as mandatory so I just skiped it. Thanks for the support!
