### ISSUE TITLE
Support import for dbt_global_connection

### ISSUE THREAD

**Issue by bramrodenburg** [dbt-labs/terraform-provider-dbtcloud#285]
## Is your feature request related to a problem? Please describe.

Recently, the [dbt_global_connection](https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest/docs/resources/global_connection) resource got added. However, it doesn't seem to support imports of existing connections. It would be great to have that.

## Describe the solution you'd like

Support import blocks and add it to the documentation for the dbt_global_connection resource.

**Comment by b-per** [comment]
After thinking about it, as it might take time to support all DWs, I am going to add `import` to `dbtcloud_global_connection` for the existing Data Warehouses first, and then add support all the Data Warehouses.

**Comment by b-per** [comment]
Added to 0.3.12

**Comment by bramrodenburg** [comment]
Thanks a lot @b-per :)
