### ISSUE TITLE
Add argument for "Target name" to dbtcloud_bigquery_credential

### ISSUE THREAD

**Issue by jenna-jordan** [dbt-labs/terraform-provider-dbtcloud#298]
## Is your feature request related to a problem? Please describe.
When a user first sets up development credentials in a project, they must manually change the Target name from "default" to "cloud" to be correctly setup in the org's infrastructure. It is very likely that someone may not know or forget to make this change. So, it would be nice to have a custom default value specified for the Target name, to reduce human error.

## Describe the solution you'd like
Add an argument target_name to the [dbtcloud_bigquery_credential](https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest/docs/resources/bigquery_credential) resource.

## Describe alternatives you've considered
Users continue to make this change manually during configuration setup

## Additional context
I've attached a screenshot of what the current default looks like for context.
![Screenshot 2024-09-18 at 5 01 33 PM](https://github.com/user-attachments/assets/50176b1b-b144-4461-b08c-aa9a7626ad6d)

**Comment by b-per** [comment]
Thanks for raising this!

I think that this is a pretty new feature! It might have been added with the introduction of global connections.

I will have a look at when I can implement it. But, with Coalesce in the next few weeks, I don't know if I will have time to do it before.

In the meantime, you can also achieve the same by setting an extended attribute on your environment and setting the value:
```
target: cloud
```
if you want the target name to dbt `cloud`

**Comment by jenna-jordan** [comment]
> Thanks for raising this!
> 
> I think that this is a pretty new feature! It might have been added with the introduction of global connections.
> 
> I will have a look at when I can implement it. But, with Coalesce in the next few weeks, I don't know if I will have time to do it before.

Totally understandable, thank you for looking into it!

> In the meantime, you can also achieve the same by setting an extended attribute on your environment and setting the value:
> 
> ```
> target: cloud
> ```
> 
> if you want the target name to dbt `cloud`

Good to know, I'll give this a try!

**Comment by b-per** [comment]
I checked a bit more this issue and didn't realize that we were talking about **developer credentials**.

In that case, the workaround I shared is the only solution to apply the same target name for all developers. Our API doesn't allow updating individual users credentials.
