### ISSUE TITLE
Environments -> The UI allows for override of the global connection defaults, but the TF resource does not

### ISSUE THREAD

**Issue by will-sargent-dbtlabs** [dbt-labs/terraform-provider-dbtcloud#303]
## Describe the bug
With the move to global connections, the global connections have sub-schemas for snowflake (and others) that allow setting the default values for database, role and warehouse.

But the dbtcloud_environment (Resource) doesn't allow for adding an override when configuring the environment.

However, that is supported in the UI.

As I understand it, these values follow an inheritance chain of:

global connection -> environment

## Error message
N/A

## Resource configuration
N/A

## Expected behavior
Allow the DWH connection specific defaults to be specified and overridden by the environment resource.

## Config (please complete the following information):
( the version can be retrieved running the command `terraform providers` )
 - dbt Cloud provider version [e.g. 0.3.18]

**Comment by b-per** [comment]
Hey @will-sargent-dbtlabs 

I am pretty sure that this is already working today and this part didn't really change with global connections.

The "overrides" mentioned are part of the `credentials` for the environment (not just the connection).
For Snowflake for example, we can provide a different database, role or warehouse in the `dbtcloud_snowflake_credential` as the ones that come from the connection.
