### ISSUE TITLE
Query history flag

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/terraform-provider-dbtcloud#304]
## Is your feature request related to a problem? Please describe.
dbt Cloud has a new ~account~ environment level feature "model query history" (https://docs.getdbt.com/docs/collaborate/model-query-history) that we should support in the provider.

## Describe the solution you'd like
An ~account~ environment level config to set this param to true.

## Describe alternatives you've considered
Enable in the UI.

## Additional context
Filing on behalf of customer.

**Comment by chrisweis** [comment]
@jeremyyeo isn't this an **environment** (not account) parameter?  In the docs link you shared it states:

> Select the **environment** marked PROD and click Settings.

**Comment by jeremyyeo** [comment]
O yes - that looks right. Not sure why I said account level. :)

**Comment by b-per** [comment]
Asking access for the feature in my account.
I don't know if we should add it to the provider before the feature is GA though as some people might try to configure it.

**Comment by b-per** [comment]
I didn't realize that it was ON for all customers but only available for some DW.

I have added it to 0.3.20 via #312
