### ISSUE TITLE
data "dbtcloud_global_connections" fails on PrivateLink connections

### ISSUE THREAD

**Issue by imre-kerr-sb1** [dbt-labs/terraform-provider-dbtcloud#309]
## Describe the bug
When there is a global connection present in the account that uses PrivateLink, the `dbtcloud_global_connections` data source fails on plan and apply.

## Error message
```
╷
│ Error: Issue when retrieving connections
│ 
│   with module.dbt_cloud[0].data.dbtcloud_global_connections.connections,
│   on modules/dbt_cloud/main.tf line 29, in data "dbtcloud_global_connections" "connections":
│   29: data "dbtcloud_global_connections" "connections" {}
│ 
│ json: cannot unmarshal string into Go struct field GlobalConnectionSummary.private_link_endpoint_id of type int64
╵
```

## Resource configuration
```
data "dbtcloud_global_connections" "connections" {}
```

## Expected behavior
Data source should get all global connections without error.

## Config
 - dbt Cloud provider version 0.3.19

**Comment by b-per** [comment]
Thanks for the report!

That's not good. 
I was already planning of doing a new release soon and I will add a fix at the same time.
