### ISSUE TITLE
Remove all prefixes in docs

### ISSUE THREAD

**Issue by GtheSheep** [dbt-labs/terraform-provider-dbtcloud#94]
dat-cloud is duped in the docs site

<img width="280" alt="Screenshot 2022-10-26 at 17 23 16" src="https://user-images.githubusercontent.com/13685708/198149868-19295883-8d0f-4497-8f28-b96001854e20.png">

**Comment by GtheSheep** [comment]
Can be done in new plugin framework using metadata

**Comment by b-per** [comment]
This is handled with the changes of 0.2.0, moving from `dbt_cloud_xxx` to `dbtcloud_xxx`.
See [docs](https://registry.terraform.io/providers/dbt-labs/dbtcloud/latest/docs/resources/bigquery_connection).
